repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
      - id: terraform_fmt

      - id: terraform_validate

      - id: terraform_docs

      - id: terraform_trivy
        args:
          - --args=--severity=HIGH,CRITICAL
          - --args=--ignorefile=__GIT_WORKING_DIR__/.trivyignore

      - id: terraform_tflint
        stages: [manual]
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-private-key      # guards the *.pem material referenced in .env
      - id: check-yaml
        args: [--allow-multiple-documents]
