name: 'Terraform Setup'
description: 'Setup Terraform with Azure OIDC authentication and caching'

inputs:
  terraform_version:
    description: 'Terraform version'
    required: false
    default: '1.9.8'
  azure_client_id:
    description: 'Azure Client ID for OIDC'
    required: true
  azure_tenant_id:
    description: 'Azure Tenant ID'
    required: true
  azure_subscription_id:
    description: 'Azure Subscription ID'
    required: true
  working_directory:
    description: 'Terraform working directory'
    required: false
    default: '.'
  backend_config_file:
    description: 'Path to backend.hcl'
    required: false
    default: ''
  cache_plugins:
    description: 'Enable provider caching'
    required: false
    default: 'true'

outputs:
  terraform_version:
    description: 'Installed Terraform version'
    value: ${{ steps.setup.outputs.terraform_version }}
  cache_hit:
    description: 'Whether cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      id: setup
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: true

    - name: Cache Terraform Plugins
      id: cache
      if: inputs.cache_plugins == 'true'
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v.5.0.2
      with:
        path: |
          ~/.terraform.d/plugin-cache
          ${{ inputs.working_directory }}/.terraform
        key: terraform-${{ runner.os }}-${{ hashFiles('**/*.tf', '**/.terraform.lock.hcl') }}
        restore-keys: |
          terraform-${{ runner.os }}-

    - name: Configure Plugin Cache
      shell: bash
      run: |
        mkdir -p ~/.terraform.d/plugin-cache
        echo 'plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc

    - name: Azure Login (OIDC)
      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
      env:
        AZURE_LOGIN_PRE_CLEANUP: true
        AZURE_LOGIN_POST_CLEANUP: true
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}

    - name: Set ARM Environment Variables
      shell: bash
      run: |
        cat >> $GITHUB_ENV << EOF
        ARM_CLIENT_ID=${{ inputs.azure_client_id }}
        ARM_TENANT_ID=${{ inputs.azure_tenant_id }}
        ARM_SUBSCRIPTION_ID=${{ inputs.azure_subscription_id }}
        ARM_USE_OIDC=true
        TF_IN_AUTOMATION=true
        TF_INPUT=false
        EOF

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        INIT_ARGS="-input=false -no-color"
        if [ -n "${{ inputs.backend_config_file }}" ]; then
          INIT_ARGS="$INIT_ARGS -backend-config=${{ inputs.backend_config_file }}"
        fi
        terraform init $INIT_ARGS