name: terraform-audit

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    name: Trivy IaC scan
    permissions:
      contents: read
      security-events: write
    uses: ianoflynnautomation/bjjeire-ci-templates/.github/workflows/iac-scan.yml@v1
    with:
      scan-path: "."
      severity: CRITICAL,HIGH
      trivyignore-file: .trivyignore
      trivy-config-file: trivy.yaml
      sarif-category: trivy-iac
