name: terraform-audit

on:
  push:
    branches: [main]
    paths:
      - "**.tf"
  pull_request:
    branches: [main]
    paths:
      - "**.tf"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    name: Run tfsec sarif report
    permissions:
      contents: read
      security-events: write
    uses: ianoflynnautomation/bjjeire-ci-templates/.github/workflows/iac-scan.yml@v1
    with:
      scan-path: "."
      severity: CRITICAL,HIGH
      trivyignore-file: .trivyignore
      # skip-dirs for .terraform lives here.
      trivy-config-file: trivy.yaml
      sarif-category: trivy-terraform
